defaults:
  - model: mae
  - loss: null
  - metrics: null


optimizer:
  # Effective LR = base_lr * batch_size / 256 (linear scaling rule)
  base_lr: 1e-4
  weight_decay: 1e-4
  betas: [0.9, 0.95]
  eps: 1e-6
  layer_decay: 1.00

scheduler:
  warmup_steps: 0.05
  min_lr: 1.0e-6
